#! usr/bin/env bash
GREETINGS=HI
STATEMENT="my name is,"
INTERROGATIVEPRONUN1=what?
INTERROGATIVEPRONUN2=who?
NAME=${1:-"Slim Shady"}
ALLITERATION=chka-chka

echo ${STATEMENT} ${INTERROGATIVEPRONUN1}
echo ${STATEMENT} ${INTERROGATIVEPRONUN2}
echo ${STATEMENT} ${ALLITERATION} ${NAME}
